name: Build
on:
  push:
    branches:
      - master

permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          registry: https://docker.super.fish
          username: robot$weathergoat+ci-cd
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            docker.super.fish/weathergoat/weathergoat:${{ github.sha }}
            docker.super.fish/weathergoat/weathergoat:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
